### ISSUE TITLE
Preview vs disabled popups

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-popups#110]
If the most recent post has disabled popups, the inline popup preview will be broken – as it uses the most recent post. 
[Reported](https://github.com/Automattic/newspack-popups/pull/108#pullrequestreview-399857949) on #108

**Comment by jeffersonrabb** [comment]
I just got burned by this one too. Two possible solutions:

1) Ignore the disabled state in campaign previews.
2) Improve the logic for choosing the post for preview so that it never selects one where campaigns are disabled.

The second is probably better. This could also be an opportunity to choose a preview post that has enough content to guarantee a natural placement of inline campaigns. Also, as of https://github.com/Automattic/newspack-plugin/pull/523 there is duplicate logic in Newspack Plugin and Newspack Popups to pick the best post. This should exist in only one place.
