### ISSUE TITLE
Overlays: Add position and size option

### ISSUE THREAD

**Issue by thomasguillot** [Automattic/newspack-popups#114]
This would allow users to choose where they want to display the overlay on the screen and how big or small it should be.

![options](https://user-images.githubusercontent.com/177929/80604760-07107500-8a2a-11ea-9c88-24a20c8d0a86.png)

_Position is inspired by CoBlocks' Hero block._

**Comment by iamstevebeatty** [comment]
On a related note, I notice the size of the pop-up changes, becoming bigger if it's top or bottom aligned, smaller in the center (see two images attached). I'd like to have something smaller and at the top or bottom. Looks like what @thomasguillot has suggested here will do that. But if I'm wishing, I'll wish big: Rather than having a tic tac toe board and choosing one spot as the placement, I'd love to see a scalable block that can be moved to the preferred spot. Then I could change the size, change the placement, and maybe even change the action for how it appears: sliding, popping up, fading in, dissolve. 
 
![Screen Shot 2020-04-29 at 11 39 24 AM](https://user-images.githubusercontent.com/48489469/80624389-39fa3f00-8a11-11ea-94f2-5c1babd68291.png)

![Screen Shot 2020-04-29 at 11 38 58 AM](https://user-images.githubusercontent.com/48489469/80624369-336bc780-8a11-11ea-93ff-712c031c7e7c.png)

**Comment by kariae** [comment]
@thomasguillot I won't say no to a little sizing specs 😅. 

Currently, I did set a default prompt size of `33.3333%` which will be the `small` size. The `medium` will be `66.6666%`, and `big` will be at `100%`.

For mobile, I think the size should always be `100%`, what are your thoughts? 

Also, in the current implementation, for screens larger than `780px`, we're setting a `min-width: 780px;` for prompts at the bottom and top of the screen, should this behavior change?

@iamstevebeatty I do like the scalable block idea, but I'm afraid that it won't be accurate at 100%.
I think we can add also an `entering effect`, @thomasguillot?

**Comment by thomasguillot** [comment]
> Currently, I did set a default prompt size of `33.3333%` which will be the small size. The medium will be `66.6666%`, and big will be at `100%`.

By default, this sounds good. We could also do something like: S: 25%, M: 50%, L: 75%, Full-width: 100%.
I wonder if we could have a filter so that a theme (e.g. newspack-theme) could set more specific sizes.

> For mobile, I think the size should always be `100%`, what are your thoughts?

Agreed, the sizes should be for large screens only.

> Also, in the current implementation, for screens larger than 780px, we're setting a min-width: 780px; for prompts at the bottom and top of the screen, should this behavior change?

I can't remember why I originally did this. I don't mind if we change the behaviour here but we will need to make sure it's not affecting current prompts.

> I think we can add also an `entering effect`

Please no 😊

> One last thing, with the new positions (top-left, top-right, ...) we'll need to add them to the `Add New Prompt` wizard popup, but I think it will be crowded, so we can skip them, and let it as it is.

Yeah, let's not worry about it.
