### ISSUE TITLE
Broken Campaign Display In Classic Posts

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-popups#137]
If a post has not been converted to Gutenberg blocks, overlay campaign content will be displayed at the top of the content, un-styled. To reproduce:

- Create a Campaign, Placement Center, Trigger: Timer, Frequency: Test Mode. Make it the Sitewide Default and publish.
- Create a normal post with Gutenberg content.
- Create a second post. Switch to Code Editor and paste in some plain text.
- View both posts. In the Gutenberg post the Campaign should function correctly, appearing after the determined delay.
- In the classic post the content of the Campaign should be visible at the top of the content with un-styled elements like the close buttons.

![newspack1 ngrok io_2020_06_07_classic-content5_](https://user-images.githubusercontent.com/1477002/83983110-cc87db00-a8f9-11ea-9c21-a7918431a708.png)

It appears the problem is that the opening `<amp-layout />` element gets wrapped in a `<p>` tag, which breaks the markup and styling. e.g.:

```
<p>		<amp-layout amp-access="popup_6901.displayPopup" amp-access-hide class="newspack-lightbox newspack-lightbox-placement-bottom " role="button" tabindex="0" id="lightbox1479347744"></p>
```

**Comment by jeffersonrabb** [comment]
If a proper fix proves elusive this branch will suppress campaigns in classic content: https://github.com/Automattic/newspack-popups/pull/138

**Comment by jeffersonrabb** [comment]
Update: the same problem occurs in posts with no content at all.

**Comment by adekbadek** [comment]
I was able to reproduce that only with an empty post, after travelling back in time to before #150. On `master`, the only issue I've found is that the campaign content is not rendered at all if the post is empty, but that's intentional: https://github.com/Automattic/newspack-popups/blob/3bae8733a17e58db779c595ea2c2c82c9beb92f4/includes/class-newspack-popups-inserter.php#L148-L150

@jeffersonrabb Please confirm if this can be closed.

**Comment by adekbadek** [comment]
Closing in favour of #520
