### ISSUE TITLE
Inline campaigns are not honoring approximate position in editor

### ISSUE THREAD

**Issue by joeboydston** [Automattic/newspack-popups#142]
_Note: So far this issue is only presenting sahanjournal.com. I cannot reproduce on a test site. But logging it here in case it comes up again._

Issue:
When logged in, the inline campaign appears at the top of the post regardless of Approximate position. When logged out, the positioning is working perfectly. 

Example post:
https://sahanjournal.com/education/dreams-coming-true-cristo-rey-students-celebrate-their-hard-earned-high-school-graduation/

**Comment by jeffersonrabb** [comment]
Similar situation was reported on The Rivard Report as well. In this screenshot, the Newsletter Campaign was set to 50% and the Donation Campaign to 80%.

![RR-double-mod](https://user-images.githubusercontent.com/1477002/84696727-ea1cfc00-af1a-11ea-830b-76fe3b967aac.png)

**Comment by jeffersonrabb** [comment]
A theory: could this be happening when the post are not processed in the order they appear in content? E.G.

Campaign ID 1: 50%
Campaign ID 2: 25%

**Comment by adekbadek** [comment]
I can reproduce "wrong inline placement" when there are more than one inline campaigns. The exact definition of wrong seems to depend on dynamic blocks in post, but in any case – the issue is caused by rendering blocks in popup insertion, [as noted](https://github.com/Automattic/newspack-popups/pull/94#discussion_r439682608) by @claudiulodro.

**Comment by jeffersonrabb** [comment]
> A theory: could this be happening when the post are not processed in the order they appear in content? 

I did some testing that seems to support the order theory:

1) Delete all Campaigns.
2) Create a campaign, Title: "Campaign 1," Placement: Inline, Position: 1%, Frequency: Test Mode. Publish it.
3) Create another campaign, Title: "Campaign 2," Placement: Inline, Position: 50%, Frequency: Test Mode. Publish it. 
4) View a long, text heavy post. The campaigns are in the right places.
5) Edit Campaign 1, change position to 50%, republish. 
6) Edit Campaign 2, change position to 1%, republish.
7) View the post again, observe the two are stacked at the beginning of the content.
8) Edit Campaign 2, change position to 30%, republish. 
9) View the post, observe the two are stacked, but ~30% of the way into content.

This seems to indicate that multiple inline popups must be processed in descending order of placement, otherwise they will be stacked at the position of the first one.
