### ISSUE TITLE
In wizard, changing frequency of a draft gives error

### ISSUE THREAD

**Issue by iamstevebeatty** [Automattic/newspack-popups#185]
To recreate:
Create a campaign, but don't publish, then close. 
In the wizard, find the campaign under Drafts, hit the three dots to the right and try to change frequency (never, once, once a day...)
You should get the error message.
Acknowledging the error doesn't take you back to Campaigns; it takes you back to main Newspack menu. 

Suggest graying out or not showing the frequency line. 

![Screen Shot 2020-07-21 at 1 14 11 PM](https://user-images.githubusercontent.com/48489469/88091453-a9855380-cb54-11ea-9461-a40205d5f3e2.png)
![Screen Shot 2020-07-21 at 1 14 23 PM](https://user-images.githubusercontent.com/48489469/88091455-aa1dea00-cb54-11ea-9f16-1db5aeb03aef.png)

**Comment by jeffersonrabb** [comment]
This potentially raises a broader question: what is the meaning of published state for Campaigns? Since Campaigns already have a Frequency control that includes Test Mode and Never, the published state doesn't really play a role. However, published state does create confusion in a few ways:

- an unpublished Campaign won't ever be seen
- Sitewide Default toggle is only shown after a Campaign has been publsihed
- The problems @iamstevebeatty raises in this issue

I'm wondering if we should do away with published state and rely solely on the Frequency setting to determine visibility rules?  

cc: @adekbadek

**Comment by adekbadek** [comment]
> This potentially raises a broader question: what is the meaning of published state for Campaigns?

I think published vs. draft is an important part of WP UX, a user is used to the fact that hitting the big button makes content public. I'd be wary of breaking that model.
Instead, I'd get rid of "never" frequency, as that is effectively like reverting a post to draft. 

Coming back to the issue, I think three solutions are possible:

1. As Steve suggested, graying out the frequency setting for draft campaigns
2. Publishing the campaign when a draft's frequency is changed
3. Handling setting the frequency of a draft campaign, without error :) 

WDYT?

**Comment by iamstevebeatty** [comment]
We have other examples in Newspack where things get published outside of
the familiar big-button experience. I always find it disconcerting that all
I have to do is flip a toggle to make the ads turn on; there's no "save
settings" or anything to make it feel official. Taking away the draft
status does simplify things. Now when you change a campaign to "never" it
goes on the "inactive" list, which just means "draft" but adds a layer. I'd
be in favor of losing "drafts" and having active/inactive as the only
statuses. But we really do need to get rid of "never" in favor of
"inactive" or "off." I demo that feature, and people always ask why I'd
create something but then set it to never show.
