### ISSUE TITLE
Inline campaign for related stories

### ISSUE THREAD

**Issue by sonjaleix** [Automattic/newspack-popups#205]
We're looking to set up an inline campaign to display related stories (via Jetpack) upon user scroll progress of X percent. It doesn't seem to be able to render related stories on single posts with an inline campaign.

**Comment by jeffersonrabb** [comment]
This was addressed several months ago in https://github.com/Automattic/newspack-popups/pull/144, and in my testing it appears to be working. Could you share details of the case where it isn't working?

**Comment by sonjaleix** [comment]
@jeffersonrabb For some reason it doesn't work on our site. What we're trying to do is adding related posts inline at a certain scroll percentage (e.g. 75%). 

Here are the steps I took to set it up, which you can replicate to test: 
- Go to Jetpack > Settings (disable option "Show related content after posts") > this is what we're currently using to display related posts at the very bottom of the post.
- Set up inline campaign with title and the related posts block: check all categories to make sure it displays across, select frequency "Every page"
- Publish inline campaign
- Go to single story to review
- What I see is the inline campaign but the related posts block doesn't output any posts. I've tested on multiple posts and the result is the same (see screenshot attached)

What am I missing?

<img width="1034" alt="Screen Shot 2020-09-11 at 5 35 21 PM" src="https://user-images.githubusercontent.com/4823744/92981053-82ad1480-f455-11ea-8c5b-66818155c9c6.png">

**Comment by sonjaleix** [comment]
Any thoughts on this @jeffersonrabb

**Comment by jeffersonrabb** [comment]
When "Show related content after posts" is switched off in Jetpack settings the Related Posts block becomes unavailable. I'm guessing you added the block to a campaign, then switched off Related Posts afterwards, which causes the block to render blank. 

The fix is to keep Related Posts switched on. This will cause Related Posts to be added at the end of the post, though, which will almost certainly come across as redundant. This can be corrected by using the approach described in https://jetpack.com/support/related-posts/customize-related-posts/ which is to add this hook:

```
function jetpackme_remove_rp() {
    if ( class_exists( 'Jetpack_RelatedPosts' ) ) {
        $jprp = Jetpack_RelatedPosts::init();
        $callback = array( $jprp, 'filter_add_target_to_dom' );
 
        remove_filter( 'the_content', $callback, 40 );
    }
}
add_action( 'wp', 'jetpackme_remove_rp', 20 );
```

We can look into an approach where this hook is applied programmatically if there are campaigns with Related Posts in them, but that's a separate issue (an enhancement rather than a bug) so I'll file separately.
