### ISSUE TITLE
Scroll-triggered overlay campaign does not show up on homepage

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-popups#217]
## To reproduce

1. Create an overlay campaign with scroll trigger, set to sitewide default 
2. Visit the homepage, observe the campaign is not displayed

---

This is intended, but is a bug nevertheless:

https://github.com/Automattic/newspack-popups/blob/11c9f3b17bcc125e9a87dfce942f03194e9c5657/includes/class-newspack-popups-inserter.php#L427-L428

**Comment by jeffersonrabb** [comment]
I'm not clear how we could do this using the `amp-position-observer` plugin,  since the trigger is defined by where the component is placed. In a column of text it's straightforward to estimate the percentage-based position, but on a homepage with a complex columnar layout where would we place it? This can be done pretty easily in vanilla Javascript using the window scroll object, but I'm not sure how it can be done in AMP.
