### ISSUE TITLE
Allow Above Site Header Placement In Non-Interactive Mode

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-popups#357]
In non-interactive mode overlay campaigns are suppressed and inline campaigns are always shown. The brand-new `above site header` placement behaves like overlays, but should instead behave like inline campaigns. This placement makes sense for breaking news and other critical announcements, which could coincide with a high traffic event. By this thinking, it would make sense to ensure these campaigns will always be shown.

**Comment by kariae** [comment]
This has been fixed with [this change](https://github.com/Automattic/newspack-popups/blob/fdc1bdd32267ad59fcd03e61c4f7369af7b41768/includes/class-newspack-popups-model.php#L469) in the is_inline function.

To test the fix:
1. Add an overlay and above header prompts.
2. Open a post and observe both prompts are showing.
3. Enable non-interactive mode from `settings`.
4. Reload the post and observe the overlay prompt not showing while the above header prompt is still there.
