### ISSUE TITLE
Error when editing Text Widget in the Customizer

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-popups#470]
**Steps to reproduce**

1. Start on a site with the Campaigns plugin activated
2. Navigate to Customize > Widgets and add a text widget, and write some text in it
3. Note the error it throws:

![image](https://user-images.githubusercontent.com/177561/110038055-17e9e100-7cf4-11eb-981f-28c1ba82e5e4.png)

4. Try to save your changes, but it won't actually save.
5. Deactivate the Campaigns plugin and repeat step 2 -4 -- it should now work. 

I'm not sure exactly what's happening here, but commenting out the following code for me made the error go away: 

https://github.com/Automattic/newspack-popups/blob/32836f12b5e498898125c3d320c6cfcf183165c9/includes/class-newspack-popups-inserter.php#L115-L120

(What it broke in the plugin is another story).

Other widgets seem to save fine in the Customizer, and if you navigate to WP Admin > Appearance > Widgets, you can edit Text Widgets there as a work-around.

**Comment by dkoo** [comment]
It's the `update_option` function in the `save_widgets_shortcoded_popup_ids` callback that causes the request to fail, for some reason—that function returns `false` (indicating that it's not successful) and also causes the "An error has occurred" message in the Customizer. When I comment out that one line, the error does not occur, which indicates that the failing `update_option` call somehow causes the whole REST request from the Customizer updating the widget content to fail.

Ideally we'd be able to look up text widgets and search for popups at the moment when we're building the `amp-access` calls in the header, but it seems like that might get pretty complex due to how hard it is to get arbitrary widget data.

**Comment by adekbadek** [comment]
This error is returned because Customizer [expects a widget to update only one option](https://github.com/WordPress/WordPress/blob/56c162fbc9867f923862f64f1b4570d885f1ff03/wp-includes/class-wp-customize-widgets.php#L1467-L1479) :/

> Ideally we'd be able to look up text widgets and search for popups at the moment when we're building the amp-access calls in the header, but it seems like that might get pretty complex due to how hard it is to get arbitrary widget data.

Yeah that would be the best solution, but I could not make it work when developing #321

**Comment by dkoo** [comment]
I tried playing with it too and couldn't make it work, either. I suppose we should keep this open as a known bug because I can't think of any way to get around it right now. The workaround: don't use the customizer to place prompts in widgets :\
