### ISSUE TITLE
Make prompts respond to flush left or right alignment. Maybe full width. 

### ISSUE THREAD

**Issue by iamstevebeatty** [Automattic/newspack-popups#483]
Enhancement (I can't label issues the normal way)

Goal: Make prompts respond to alignment control when contents are grouped. 

A groups can usually be aligned left or right, making it half the column width, with type wrapping. They can also be full or wide width. 

![Screen Shot 2021-03-12 at 1 24 47 PM](https://user-images.githubusercontent.com/48489469/110989010-e5189c00-8336-11eb-83eb-e4f98edcbfc6.png)

I tried this with prompts, and the left aligned looked promising, with some stray lines at the top. Right didn't do anything. Setting it at wide width made it appear on the right, still with the stray lines. So it's rather unpredictable now.

**Comment by dkoo** [comment]
@iamstevebeatty I'm wary of supporting the wide and full-width alignment options because the inline prompts can appear anywhere in the content, and I'm not sure how to avoid colliding with other elements on the page (such as the sidebar or other injected elements). But #513 should help with this by allowing you to at least hide the ugly border and padding for prompts that contain only a group block floated left or right.
