### ISSUE TITLE
Reinstate manual placement

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-popups#538]
Manual placements were superseded by and converted to custom placements in #467, but they are needed as a feature. 

A user should be able to just place a prompt in an arbitrary place on the site, and disable programmatic insertion of this prompt. This is possible with custom placements, **but** until there are more than three such prompts - as the only way of disabling programmatic insertion is assigning to custom placements and then instead of using the custom placement block, inserting prompts using shortcodes. 

## Use case:

Four prompts, each should be possible to be placed ~programatically~ _manually_ on the same page.

**Comment by dkoo** [comment]
Summary of how we're planning to resolve this:

1. Shortcode blocks will ignore any API-related logic that might restrict a prompt from being displayed. This means:
  - Overlay and above-header prompts will be displayed like inline prompts when placed via a shortcode in post content.
  - There may be duplication on a single post if a prompt is both placed via shortcode AND is displayed programmatically via the API.
2. We will create a new block called the **Single Prompt** block which will display a UI similar to the Newspack Listings UI to select a specific listing for a Curated List block (an autocomplete field to search for prompts by name, plus a list of the most recently published ~10 prompts to select from).
  - If no prompt is selected, the block will display nothing on the front-end.
  - Once a prompt is selected, on the front-end this block will render the prompt as a shortcode, meaning it will behave exactly the same as described in (1) above.
  - The prompt selection should be clearable or swappable in the editor.
3. We will reintroduce a "Manual only" option as a placement option. This is to cover a use-case that's been missing since the introduction of custom placements.
  - If a prompt is set to "Manual only" placement, it will never be inserted programmatically under any circumstances.
  - The only way to display a prompt with this placement is to place it manually via a shortcode or a Single Prompt block.

**Comment by adekbadek** [comment]
@dkoo @thomasguillot WDYT about the following related changes:

1. When a prompt is an overlay one, rename the "Placement" label to "Position":

![image](https://user-images.githubusercontent.com/7383192/117259520-692a6400-ae4e-11eb-8d85-64e7a75a6af8.png)

2. When a prompt is inline, rename "Placement" to "Automatic placement", the proposed "Manual only" to "none", and add a more descriptive help text:

![image](https://user-images.githubusercontent.com/7383192/117259683-9414b800-ae4e-11eb-90ea-3e3d0ae69195.png)

?

**Comment by dkoo** [comment]
@adekbadek Good suggestions—"Position" or "Screen Position" makes sense to me for overlays.

For inline prompts, what if we kept the label as "Placement" and "Manual only" named as such, but dynamically update the help text based on the option selected?

* For "Above Header": `The prompt will be automatically inserted at the very top of the page, above the header.`
* For "In article content": `The prompt will be automatically inserted about 30% into article content.` (or whatever the position is set to)
* For any custom placement: `The prompt will appear where <custom placement name> is inserted using the Custom Placement block.`
* For "Manual only": `The prompt will appear only where inserted using the Prompt block.`

We could also dynamically update the help text for overlay positions. I suggest this because I still don't think of custom placements as being a truly "automatic" placement—it's more of a manual placement for prompts of multiple segments.
