### ISSUE TITLE
Block-count-based insertion

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-popups#623]
## As is

An inline prompt can be inserted based on percentage

## To be 

Inline prompts should be possible to insert at block-count positions, e.g. after 2nd block

**Comment by dkoo** [comment]
Question: how do we handle nested blocks?

**Comment by adekbadek** [comment]
Top-level group blocks could be "unpacked", so to speak, for the purposes of insertion. But most news site content is a series of un-nested blocks, so while a significant one, I'd still treat it as an edge case.

**Comment by aschweigert** [comment]
This is particularly an issue with sites using SCAIP. *Technically* there is no collision but it's not ideal to show an ad right before or after a CTA so ideally there would be more coordination between ad insertion and how prompts are displayed. It's a tricky issue but worth solving so we're a bit more consistent in how elements are inserted into articles.

**Comment by miguelpeixe** [comment]
In this case, it should be handled by whichever plugin executes its logic last, so it can parse the inserted block/content and alter its own insertion accordingly.

Currently, the Campaigns plugin runs first, with priority `1`, and SCAIP with priority `5`. But I personally think it should be the other way around.

Campaigns have recently implemented a [new logic to condition its placement based on block alignment to avoid layout disruption](https://github.com/Automattic/newspack-popups/pull/647). That could also be the case for ads if it executes last.

I actually suggest it should have a priority higher than the default `10`, so it can parse any scenario. That might not be possible due to the core `render_block()` filter, which wouldn't allow us to parse block attributes. Must double-check.
