### ISSUE TITLE
"Sitewide default" is confusing as the effective "on" switch

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-popups#63]
A publisher had a popup that was configured and published but wasn't appearing and couldn't understand why. I looked and also couldn't see anything wrong with the popup and why it wasn't appearing. @claudiulodro pointed out that the popup (which was the only one published with only one other draft available) didn't have the "Sitewide Default" checkbox selected.

<img width="317" alt="Screen Shot 2020-02-20 at 6 32 46 AM" src="https://user-images.githubusercontent.com/136342/74946770-b52bed00-53f1-11ea-95ff-65207209281c.png">

This effectively made that checkbox an "on" switch but without that situation being clear to the user.

Mine, and the publisher's, assumption was that a non-draft popup would show up. That seems like a logical assumption to make and I would suggest the default should be sitewide, rather than needing to explicitly select that.

Where there are multiple popups I'd suggest a general rule: specificity is supreme.

Under that 'rule', a popup without filters would display on every page, while a popup targeted to a specific category would appear only on that category as well as overriding any less-specific popups.

**Comment by jeffersonrabb** [comment]
In the original implementation, there was no Sitewide Default checkbox and the most recent published Pop-up with no categories would display everywhere—in other words, exactly what you're describing. We moved away from this for several reasons:

1) It better matched the UI in the Newspack Plugin Engagement Wizard. Discussion here: https://github.com/Automattic/newspack-plugin/pull/409

2) Because Pop-ups are such an easily abused feature, we wanted to err on the side of caution. By making sitewide default an explicit choice we protect against a situation where a publication shows pop-ups to their customers unintentionally or indiscriminately.

Based on these rationales I'm inclined to leave the functionality as it is, but improve the UI so it's clearer to the customer that this choice needs to be made explicitly. @thomasguillot any ideas?

**Comment by thomasguillot** [comment]
> Based on these rationales I'm inclined to leave the functionality as it is,

Yes, I agree.

> but improve the UI so it's clearer to the customer that this choice needs to be made explicitly.

In the editor, we should probably change this to a toggle and add some description to it.

**Comment by adekbadek** [comment]
"Sitewide default" is not a feature anymore, closing.
