### ISSUE TITLE
Add segment name to Newspack Announcement events

### ISSUE THREAD

**Issue by aschweigert** [Automattic/newspack-popups#679]
Asana: https://app.asana.com/0/1200942827698993/1201001433518035
Details: https://docs.google.com/document/d/18dBs-2PiYre8msDaZswRdciSmqExVfMrN9GgpaO9qsg/edit#heading=h.88b3ppvknsme

**Comment by dkoo** [comment]
@aschweigert Adam B [suggests](https://github.com/Automattic/newspack-popups/pull/830#issuecomment-1075102969) we add the segment names to the Event Label instead of Event Category. He says that the Event Category should be a single phrase that describes **all** prompts, and adding the segments to this field would defeat that purpose. Do you think this solves the request at hand?

**Comment by aschweigert** [comment]
Brian's objection here seems to have been mostly re: overloading the Event Label field. It's possible in GA to filter by Category or Label so I think either is probably fine. If the consensus is that appending it to the Event Label is more backwards compatible and still gets us what we need here then I'm ok with that.

**Comment by dkoo** [comment]
Sounds good. I think adding the segment to the Event Label field is potentially less dangerous than altering the Event Category field, so I moved it there. The Event Label can be pretty long, but it should still be filterable/searchable by the segment name, so functionality over beauty, right?
