### ISSUE TITLE
Post-login data reconciliation

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-popups#901]
Consider the following scenario:

1. User logs in (as a site subscriber) on device A and reads a few articles 
2. Then they view the site, not logged in, on a different device, B, and subscribe to the newsletter
3. They log in on device B
4. When they again browse on device A

At point 3. the anonymous data (containing the newsletter subscription) should be reconciled with the identifiable data, so that at point 4. they are considered a subscriber (for segmentation)

**Comment by adekbadek** [comment]
Another case: post-pre-authentication reconciliation:

1. User reads three articles, anonymously
2. User pre-authenticaticates with the email of an existing user

At this point, their segmentation data should be reconciled. In other words, the segmentation data should be reconciled anytime an anonymous reader provides and email address.

Maybe the client-id to reader relationship should be redefined as many-to-one.

**Comment by dkoo** [comment]
#978 is a PR in progress that attempts to address this issue. When a reader provides a unique identifier such as an email address or user account, we look up unique client IDs from any past reader events that share the same identifier and then update all associated reader records with all client IDs. Then, whenever getting reader events, if the reader record has multiple client IDs associated with it, we get events for all of those client IDs instead of just the current one.

There are still a few kinks to work out, but it seems to solve this issue with minimal code refactoring.
