### ISSUE TITLE
Logged-in users receiving prompts for "does not have account" segment

### ISSUE THREAD

**Issue by miguelpeixe** [Automattic/newspack-popups#928]
<img width="1304" alt="image" src="https://user-images.githubusercontent.com/820752/182165650-422850b5-e309-475b-84bb-477699ed3fbb.png">

The above prompt is segmented for anonymous readers only and this was shown to an authenticated admin. You can see that the registration block shows as resolved, because its the default display for logged in users.

**Comment by adekbadek** [comment]
This is reproducible like so:

1. Publish a prompt segmented to anonymous readers
2. In a new session, visit `/wp-admin` direcly and log in 
3. From admin panel, go to the site's front-end
4. You'll see the prompt 

This is because it's the first view in the session, and thus Campaigns does not yet store any events related to this client – for Campaigns it's an anonymous session. It's an issue with the event-based segmentation logic – the login event happened in the admin area, not on site's frontend, and thus was not reported to Campaigns. 

The solution should override the has-user-account check if the user is logged in.

**Comment by dkoo** [comment]
This is also reproducible on the front-end if logging in via the WooCommerce My Account page, which is how I did it on my end (and forgot to mention in the testing steps).

**Comment by adekbadek** [comment]
…or generally, if logging in via any page that has Campaigns disabled or unavailable (admin).
